### ISSUE TITLE
Not an issue.  Question regarding data

### ISSUE THREAD

**Issue by StudentOfLimnology** [cndbain/lakemendotabuoy#10]
First of all thank you for writing the app.  Though I check the GAMIS page daily from my PC, it's nice to have something to carry with me.  

At 1701 today, the Lake Mendota Buoy app under _Additional_ shows Oxygen: 207.1, Oxygen saturation: 16.6.  At what depth is that?  Is there any place that shows O2 PPM from the surface down to 10m or 15m?  I'm interested to see at what depth the lake becomes anoxic.  Thanks.

Regards, JT

**Comment by cndbain** [comment]
Hi!  I'm glad you're enjoying the app.  It's actually just serving the data
the UW Madison is making available:

http://metobs.ssec.wisc.edu/buoy/

And they would have more information about the depth where they're
measuring the oxygen saturation.

Best regards,

Candace

**Comment by cndbain** [comment]
Just clean-up
