### ISSUE TITLE
Bouy app

### ISSUE THREAD

**Issue by tsneidin** [cndbain/lakemendotabuoy#9]
Is not working for me this year, only showed the bouy down for the winter.

**Comment by cndbain** [comment]
Thanks for the heads-up, I hadn't seen that the buoy was back in the water.  I have a switch file at:

https://s3-us-west-2.amazonaws.com/lakemendotabuoy/buoy_status.json

So the app doesn't display bad data when the buoy is out of the water in the winter, it's turned back on now.
